import wfdb
import pandas as pd
import numpy as np
import os
from tqdm import tqdm

base_path = "ecg-data-physionet/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.3"
csv_path = os.path.join(base_path, "ptbxl_database.csv")
scp_path = os.path.join(base_path, "scp_statements.csv")
records_path = os.path.join(base_path, "records500")

df = pd.read_csv(csv_path)

# Drop unnecessary columns
cols_to_drop = ['filename_lr', 'nurse', 'site', 'device', 'validated_by',
                'second_opinion', 'initial_autogenerated_report',
                'validated_by_human']
df = df.drop(columns=cols_to_drop)

print("Cleaned DataFrame shape:", df.shape)
df.head(3)

def get_norm_score(scp_dict_str):
    try:
        d = eval(scp_dict_str)
        return d.get('NORM', 0.0)
    except:
        return 0.0

df['norm_score'] = df['scp_codes'].apply(get_norm_score)

df_norm = df[df['norm_score'] > 75]
df_abnorm = df[df['norm_score'] <= 75]

print("Normal ECGs:", len(df_norm))
print("Abnormal ECGs:", len(df_abnorm))

df_norm.to_csv("normal_records.csv", index=False)
df_abnorm.to_csv("abnormal_records.csv", index=False)

output_dir = "ecg_npy"
os.makedirs(output_dir, exist_ok=True)

for idx, row in tqdm(df_norm.iterrows(), total=len(df_norm)):
    try:
        # Extract the record path from CSV
        record_rel_path = row['filename_hr']
        record_path = os.path.join(base_path, f"{record_rel_path}")

        # Read the ECG record
        signals, fields = wfdb.rdsamp(record_path)

        # Save signal as numpy array
        np.save(os.path.join(output_dir, f"{row['ecg_id']}_hr.npy"), signals.astype(np.float32))
    except Exception as e:
        print(f"Error with {row['filename_hr']}: {e}")

print("All normal ECGs processed and saved as .npy files.")
